.\" Created from Texinfo source by yat2m 1.51
.TH GPGPARSEMAIL 1 2024-11-22 "GnuPG 2.5.2" "GNU Privacy Guard 2.6"
.SH NAME
.B gpgparsemail
\- Parse a mail message into an annotated format
.SH SYNOPSIS
.B  gpgparsemail
.RI [ options ]
.RI [ file ]

.SH DESCRIPTION
The \fBgpgparsemail\fP is a utility currently only useful for
debugging.  Run it with \fB\-\-help\fP for usage information.



